ALTER TABLE "User" ADD COLUMN "followers" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "following" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "posts" INTEGER NOT NULL DEFAULT 0;
